esphome:
  name: home35
  friendly_name: Home 3.5"

substitutions:
  home_page: printers

packages:
  common: !include common.yaml
  device: !include devices/JC3248W535.yaml
  layout: !include layouts/480x320.yaml
