esphome:
  name: home35
  friendly_name: Home 3.5"

substitutions:
  home_page: printers

packages:
  common: !include common.yaml
  device: !include devices/JC3248W535.yaml
  layout: !include layouts/480x320-home.yaml
  idle: !include features/idle/idle.yaml
  ceiling: !include features/idle/sun.yaml
  sleep_clock: !include features/sleep_clock/sleep_clock.yaml
  memory: !include features/diagnostics/memory.yaml
  psram: !include features/diagnostics/psram.yaml
