# required vars:
# - uid
# - entity_id
# - unit

sensor:
  - id: ${uid}_widget_sensor
    platform: homeassistant
    entity_id: ${entity_id}
    on_value:
      - lvgl.label.update:
          id: ${uid}_widget_value
          text: !lambda return std::to_string((int) lroundf(x)) + "${unit}";
